version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: flightpath-docker
    ports:
      - 8080:80
    volumes:
      - ./public:/srv/app
      - ./log:/var/log/apache2
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: demo
      DB_USERNAME: demo
      DB_PASSWORD: demo
  mysql:
    image: mysql:5.6
    ports:
      - 13306:3306
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
      - ./mysql:/home
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_ROOT_PASSWORD: demo
